/*
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.dsl.gratext.ui.internal.GratextActivator;

public class GratextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GratextActivator.getInstance().getInjector("org.xtext.dsl.gratext.Gratext");
	}

}
