/*
 * generated by Xtext 2.11.0
 */
package org.xtext.dsl.gratext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGratextScopeProvider extends DelegatingScopeProvider {
}
