/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.ui.wizard;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.resource.FileExtensionProvider;

/**
 * @author :Jose antonio de Benito Suarez
 * Clase utilizada para que el usuario pueda crear un nuevo proyecto de este tipo de forma sencilla
 */
@SuppressWarnings("all")
public class GratextNewProjectWizardInitialContents {
  @Inject
  private FileExtensionProvider fileExtensionProvider;
  
  public void generateInitialContents(final IFileSystemAccess2 fsa) {
    String _primaryFileExtension = this.fileExtensionProvider.getPrimaryFileExtension();
    String _plus = ("src/model/Model." + _primaryFileExtension);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("Granja: BENI1");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Centralita:DELAVAL ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Usuario: DOS");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("Contraseña: \"nueva\"");
    _builder.newLine();
    _builder.append("Dispositivos{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Codigo:CODI1 Sensor ROTURA_CRISTAL quiero ESTADO \' ESTADO el/la ROTURA_CRISTAL\'");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Codigo: CODI2 Sensor TEMPERATURA \"AMBIENTE\"  quiero ESTADO \' ESTADO el/la TEMPERATURA\'");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Codigo: CODI3 Sensor CAMARA quiero SACAR 20 FOTOS\' SACAR 20 FOTOS del CAMARA\'");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile(_plus, _builder);
  }
}
