/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.gratext.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.dsl.gratext.gratext.Dispositivos;
import org.xtext.dsl.gratext.gratext.Granja;
import org.xtext.dsl.gratext.gratext.GratextPackage;
import org.xtext.dsl.gratext.gratext.Tipo;
import org.xtext.dsl.gratext.gratext.contrasena;
import org.xtext.dsl.gratext.gratext.usuario;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Granja</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.gratext.gratext.impl.GranjaImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.gratext.gratext.impl.GranjaImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.dsl.gratext.gratext.impl.GranjaImpl#getUsuario <em>Usuario</em>}</li>
 *   <li>{@link org.xtext.dsl.gratext.gratext.impl.GranjaImpl#getContrasena <em>Contrasena</em>}</li>
 *   <li>{@link org.xtext.dsl.gratext.gratext.impl.GranjaImpl#getDispositivos <em>Dispositivos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GranjaImpl extends MinimalEObjectImpl.Container implements Granja
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final Tipo TIPO_EDEFAULT = Tipo.DELAVAL;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected Tipo tipo = TIPO_EDEFAULT;

  /**
   * The cached value of the '{@link #getUsuario() <em>Usuario</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsuario()
   * @generated
   * @ordered
   */
  protected usuario usuario;

  /**
   * The cached value of the '{@link #getContrasena() <em>Contrasena</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContrasena()
   * @generated
   * @ordered
   */
  protected contrasena contrasena;

  /**
   * The cached value of the '{@link #getDispositivos() <em>Dispositivos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDispositivos()
   * @generated
   * @ordered
   */
  protected EList<Dispositivos> dispositivos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GranjaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GratextPackage.Literals.GRANJA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tipo getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipo(Tipo newTipo)
  {
    Tipo oldTipo = tipo;
    tipo = newTipo == null ? TIPO_EDEFAULT : newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public usuario getUsuario()
  {
    return usuario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUsuario(usuario newUsuario, NotificationChain msgs)
  {
    usuario oldUsuario = usuario;
    usuario = newUsuario;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__USUARIO, oldUsuario, newUsuario);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUsuario(usuario newUsuario)
  {
    if (newUsuario != usuario)
    {
      NotificationChain msgs = null;
      if (usuario != null)
        msgs = ((InternalEObject)usuario).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GratextPackage.GRANJA__USUARIO, null, msgs);
      if (newUsuario != null)
        msgs = ((InternalEObject)newUsuario).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GratextPackage.GRANJA__USUARIO, null, msgs);
      msgs = basicSetUsuario(newUsuario, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__USUARIO, newUsuario, newUsuario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public contrasena getContrasena()
  {
    return contrasena;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContrasena(contrasena newContrasena, NotificationChain msgs)
  {
    contrasena oldContrasena = contrasena;
    contrasena = newContrasena;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__CONTRASENA, oldContrasena, newContrasena);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContrasena(contrasena newContrasena)
  {
    if (newContrasena != contrasena)
    {
      NotificationChain msgs = null;
      if (contrasena != null)
        msgs = ((InternalEObject)contrasena).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GratextPackage.GRANJA__CONTRASENA, null, msgs);
      if (newContrasena != null)
        msgs = ((InternalEObject)newContrasena).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GratextPackage.GRANJA__CONTRASENA, null, msgs);
      msgs = basicSetContrasena(newContrasena, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GratextPackage.GRANJA__CONTRASENA, newContrasena, newContrasena));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Dispositivos> getDispositivos()
  {
    if (dispositivos == null)
    {
      dispositivos = new EObjectContainmentEList<Dispositivos>(Dispositivos.class, this, GratextPackage.GRANJA__DISPOSITIVOS);
    }
    return dispositivos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GratextPackage.GRANJA__USUARIO:
        return basicSetUsuario(null, msgs);
      case GratextPackage.GRANJA__CONTRASENA:
        return basicSetContrasena(null, msgs);
      case GratextPackage.GRANJA__DISPOSITIVOS:
        return ((InternalEList<?>)getDispositivos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GratextPackage.GRANJA__NAME:
        return getName();
      case GratextPackage.GRANJA__TIPO:
        return getTipo();
      case GratextPackage.GRANJA__USUARIO:
        return getUsuario();
      case GratextPackage.GRANJA__CONTRASENA:
        return getContrasena();
      case GratextPackage.GRANJA__DISPOSITIVOS:
        return getDispositivos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GratextPackage.GRANJA__NAME:
        setName((String)newValue);
        return;
      case GratextPackage.GRANJA__TIPO:
        setTipo((Tipo)newValue);
        return;
      case GratextPackage.GRANJA__USUARIO:
        setUsuario((usuario)newValue);
        return;
      case GratextPackage.GRANJA__CONTRASENA:
        setContrasena((contrasena)newValue);
        return;
      case GratextPackage.GRANJA__DISPOSITIVOS:
        getDispositivos().clear();
        getDispositivos().addAll((Collection<? extends Dispositivos>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GratextPackage.GRANJA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GratextPackage.GRANJA__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
      case GratextPackage.GRANJA__USUARIO:
        setUsuario((usuario)null);
        return;
      case GratextPackage.GRANJA__CONTRASENA:
        setContrasena((contrasena)null);
        return;
      case GratextPackage.GRANJA__DISPOSITIVOS:
        getDispositivos().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GratextPackage.GRANJA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GratextPackage.GRANJA__TIPO:
        return tipo != TIPO_EDEFAULT;
      case GratextPackage.GRANJA__USUARIO:
        return usuario != null;
      case GratextPackage.GRANJA__CONTRASENA:
        return contrasena != null;
      case GratextPackage.GRANJA__DISPOSITIVOS:
        return dispositivos != null && !dispositivos.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipo: ");
    result.append(tipo);
    result.append(')');
    return result.toString();
  }

} //GranjaImpl
