/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.gratext;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Estado</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.gratext.gratext.GratextPackage#getEstado()
 * @model
 * @generated
 */
public enum Estado implements Enumerator
{
  /**
   * The '<em><b>AMBIENTE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AMBIENTE_VALUE
   * @generated
   * @ordered
   */
  AMBIENTE(0, "AMBIENTE", "AMBIENTE"),

  /**
   * The '<em><b>INTERNA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTERNA_VALUE
   * @generated
   * @ordered
   */
  INTERNA(1, "INTERNA", "INTERNA"),

  /**
   * The '<em><b>NEVERA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NEVERA_VALUE
   * @generated
   * @ordered
   */
  NEVERA(2, "NEVERA", "NEVERA"),

  /**
   * The '<em><b>MECEDORA</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MECEDORA_VALUE
   * @generated
   * @ordered
   */
  MECEDORA(3, "MECEDORA", "MECEDORA"),

  /**
   * The '<em><b>DEPOSITO LECHE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEPOSITO_LECHE_VALUE
   * @generated
   * @ordered
   */
  DEPOSITO_LECHE(4, "DEPOSITO_LECHE", "DEPOSITO_LECHE");

  /**
   * The '<em><b>AMBIENTE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>AMBIENTE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AMBIENTE
   * @model
   * @generated
   * @ordered
   */
  public static final int AMBIENTE_VALUE = 0;

  /**
   * The '<em><b>INTERNA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INTERNA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTERNA
   * @model
   * @generated
   * @ordered
   */
  public static final int INTERNA_VALUE = 1;

  /**
   * The '<em><b>NEVERA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NEVERA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NEVERA
   * @model
   * @generated
   * @ordered
   */
  public static final int NEVERA_VALUE = 2;

  /**
   * The '<em><b>MECEDORA</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MECEDORA</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MECEDORA
   * @model
   * @generated
   * @ordered
   */
  public static final int MECEDORA_VALUE = 3;

  /**
   * The '<em><b>DEPOSITO LECHE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DEPOSITO LECHE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DEPOSITO_LECHE
   * @model
   * @generated
   * @ordered
   */
  public static final int DEPOSITO_LECHE_VALUE = 4;

  /**
   * An array of all the '<em><b>Estado</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Estado[] VALUES_ARRAY =
    new Estado[]
    {
      AMBIENTE,
      INTERNA,
      NEVERA,
      MECEDORA,
      DEPOSITO_LECHE,
    };

  /**
   * A public read-only list of all the '<em><b>Estado</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Estado> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Estado</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Estado get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Estado result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Estado</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Estado getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Estado result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Estado</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Estado get(int value)
  {
    switch (value)
    {
      case AMBIENTE_VALUE: return AMBIENTE;
      case INTERNA_VALUE: return INTERNA;
      case NEVERA_VALUE: return NEVERA;
      case MECEDORA_VALUE: return MECEDORA;
      case DEPOSITO_LECHE_VALUE: return DEPOSITO_LECHE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Estado(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Estado
