/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.gratext;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.gratext.gratext.GratextPackage
 * @generated
 */
public interface GratextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GratextFactory eINSTANCE = org.xtext.dsl.gratext.gratext.impl.GratextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Granja</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Granja</em>'.
   * @generated
   */
  Granja createGranja();

  /**
   * Returns a new object of class '<em>Dispositivos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dispositivos</em>'.
   * @generated
   */
  Dispositivos createDispositivos();

  /**
   * Returns a new object of class '<em>accion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>accion</em>'.
   * @generated
   */
  accion createaccion();

  /**
   * Returns a new object of class '<em>usuario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>usuario</em>'.
   * @generated
   */
  usuario createusuario();

  /**
   * Returns a new object of class '<em>contrasena</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>contrasena</em>'.
   * @generated
   */
  contrasena createcontrasena();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GratextPackage getGratextPackage();

} //GratextFactory
