/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.gratext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>usuario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.gratext.gratext.usuario#getUsuario <em>Usuario</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.gratext.gratext.GratextPackage#getusuario()
 * @model
 * @generated
 */
public interface usuario extends EObject
{
  /**
   * Returns the value of the '<em><b>Usuario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Usuario</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usuario</em>' attribute.
   * @see #setUsuario(String)
   * @see org.xtext.dsl.gratext.gratext.GratextPackage#getusuario_Usuario()
   * @model
   * @generated
   */
  String getUsuario();

  /**
   * Sets the value of the '{@link org.xtext.dsl.gratext.gratext.usuario#getUsuario <em>Usuario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Usuario</em>' attribute.
   * @see #getUsuario()
   * @generated
   */
  void setUsuario(String value);

} // usuario
