/**
 * generated by Xtext 2.11.0
 */
package org.xtext.dsl.gratext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dsl.gratext.GratextRuntimeModule;
import org.xtext.dsl.gratext.GratextStandaloneSetup;
import org.xtext.dsl.gratext.ide.GratextIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GratextIdeSetup extends GratextStandaloneSetup {
  @Override
  public Injector createInjector() {
    GratextRuntimeModule _gratextRuntimeModule = new GratextRuntimeModule();
    GratextIdeModule _gratextIdeModule = new GratextIdeModule();
    return Guice.createInjector(Modules2.mixin(_gratextRuntimeModule, _gratextIdeModule));
  }
}
