/**
 * generated by Xtext 2.11.0
 */
package org.xtext.dsl.gratext.ide;

import org.xtext.dsl.gratext.ide.AbstractGratextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GratextIdeModule extends AbstractGratextIdeModule {
}
