/*
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class GratextProjectInfo extends DefaultProjectInfo {

}
