/*
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class GratextWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public GratextWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
