/*
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.dsl.gratext.gratext.Dispositivos;
import org.xtext.dsl.gratext.gratext.Granja;
import org.xtext.dsl.gratext.gratext.GratextPackage;
import org.xtext.dsl.gratext.gratext.accion;
import org.xtext.dsl.gratext.gratext.login;
import org.xtext.dsl.gratext.gratext.numero;
import org.xtext.dsl.gratext.services.GratextGrammarAccess;

@SuppressWarnings("all")
public class GratextSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GratextGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GratextPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GratextPackage.DISPOSITIVOS:
				sequence_Dispositivos(context, (Dispositivos) semanticObject); 
				return; 
			case GratextPackage.GRANJA:
				sequence_Granja(context, (Granja) semanticObject); 
				return; 
			case GratextPackage.ACCION:
				sequence_accion(context, (accion) semanticObject); 
				return; 
			case GratextPackage.LOGIN:
				sequence_login(context, (login) semanticObject); 
				return; 
			case GratextPackage.NUMERO:
				sequence_numero(context, (numero) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Dispositivos returns Dispositivos
	 *
	 * Constraint:
	 *     (codigo=ID nombre=TiposDispositivo temperatura=STRING? accion=accion)
	 */
	protected void sequence_Dispositivos(ISerializationContext context, Dispositivos semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Granja returns Granja
	 *
	 * Constraint:
	 *     (nombreGranja=ID tipo=Tipo login=login? dispositivos+=Dispositivos*)
	 */
	protected void sequence_Granja(ISerializationContext context, Granja semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     accion returns accion
	 *
	 * Constraint:
	 *     (nombreAccion=NombreAccion numero=numero? descripcion=STRING?)
	 */
	protected void sequence_accion(ISerializationContext context, accion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     login returns login
	 *
	 * Constraint:
	 *     (usuario=ID contrasena=STRING)
	 */
	protected void sequence_login(ISerializationContext context, login semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GratextPackage.Literals.LOGIN__USUARIO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GratextPackage.Literals.LOGIN__USUARIO));
			if (transientValues.isValueTransient(semanticObject, GratextPackage.Literals.LOGIN__CONTRASENA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GratextPackage.Literals.LOGIN__CONTRASENA));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLoginAccess().getUsuarioIDTerminalRuleCall_1_0(), semanticObject.getUsuario());
		feeder.accept(grammarAccess.getLoginAccess().getContrasenaSTRINGTerminalRuleCall_3_0(), semanticObject.getContrasena());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     numero returns numero
	 *
	 * Constraint:
	 *     (idNumero=idNumero datos=Datos)
	 */
	protected void sequence_numero(ISerializationContext context, numero semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GratextPackage.Literals.NUMERO__ID_NUMERO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GratextPackage.Literals.NUMERO__ID_NUMERO));
			if (transientValues.isValueTransient(semanticObject, GratextPackage.Literals.NUMERO__DATOS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GratextPackage.Literals.NUMERO__DATOS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNumeroAccess().getIdNumeroIdNumeroParserRuleCall_0_0(), semanticObject.getIdNumero());
		feeder.accept(grammarAccess.getNumeroAccess().getDatosDatosEnumRuleCall_1_0(), semanticObject.getDatos());
		feeder.finish();
	}
	
	
}
