/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.dsl.gratext.ui.AbstractGratextUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GratextUiModule extends AbstractGratextUiModule {
  public GratextUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
