/**
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext;

import org.xtext.dsl.gratext.AbstractGratextRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GratextRuntimeModule extends AbstractGratextRuntimeModule {
}
