/*
 * generated by Xtext 2.10.0
 */
package org.xtext.dsl.gratext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GratextGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GranjaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.Granja");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGranjaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreGranjaAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreGranjaIDTerminalRuleCall_1_0 = (RuleCall)cNombreGranjaAssignment_1.eContents().get(0);
		private final Keyword cCentralitaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTipoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTipoTipoEnumRuleCall_3_0 = (RuleCall)cTipoAssignment_3.eContents().get(0);
		private final Assignment cLoginAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLoginLoginParserRuleCall_4_0 = (RuleCall)cLoginAssignment_4.eContents().get(0);
		private final Keyword cDispositivosKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cDispositivosAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDispositivosDispositivosParserRuleCall_6_0 = (RuleCall)cDispositivosAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Granja:
		//	'Granja:' nombreGranja=ID
		//	'Centralita:' tipo=Tipo
		//	login=login?
		//	'Dispositivos{' dispositivos+=Dispositivos* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Granja:' nombreGranja=ID 'Centralita:' tipo=Tipo login=login? 'Dispositivos{' dispositivos+=Dispositivos* '}'
		public Group getGroup() { return cGroup; }
		
		//'Granja:'
		public Keyword getGranjaKeyword_0() { return cGranjaKeyword_0; }
		
		//nombreGranja=ID
		public Assignment getNombreGranjaAssignment_1() { return cNombreGranjaAssignment_1; }
		
		//ID
		public RuleCall getNombreGranjaIDTerminalRuleCall_1_0() { return cNombreGranjaIDTerminalRuleCall_1_0; }
		
		//'Centralita:'
		public Keyword getCentralitaKeyword_2() { return cCentralitaKeyword_2; }
		
		//tipo=Tipo
		public Assignment getTipoAssignment_3() { return cTipoAssignment_3; }
		
		//Tipo
		public RuleCall getTipoTipoEnumRuleCall_3_0() { return cTipoTipoEnumRuleCall_3_0; }
		
		//login=login?
		public Assignment getLoginAssignment_4() { return cLoginAssignment_4; }
		
		//login
		public RuleCall getLoginLoginParserRuleCall_4_0() { return cLoginLoginParserRuleCall_4_0; }
		
		//'Dispositivos{'
		public Keyword getDispositivosKeyword_5() { return cDispositivosKeyword_5; }
		
		//dispositivos+=Dispositivos*
		public Assignment getDispositivosAssignment_6() { return cDispositivosAssignment_6; }
		
		//Dispositivos
		public RuleCall getDispositivosDispositivosParserRuleCall_6_0() { return cDispositivosDispositivosParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class LoginElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.login");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUsuarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUsuarioAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUsuarioIDTerminalRuleCall_1_0 = (RuleCall)cUsuarioAssignment_1.eContents().get(0);
		private final Keyword cContraseAKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cContrasenaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cContrasenaSTRINGTerminalRuleCall_3_0 = (RuleCall)cContrasenaAssignment_3.eContents().get(0);
		
		//login:
		//	'Usuario:' usuario=ID
		//	'Contraseña:' contrasena=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'Usuario:' usuario=ID 'Contraseña:' contrasena=STRING
		public Group getGroup() { return cGroup; }
		
		//'Usuario:'
		public Keyword getUsuarioKeyword_0() { return cUsuarioKeyword_0; }
		
		//usuario=ID
		public Assignment getUsuarioAssignment_1() { return cUsuarioAssignment_1; }
		
		//ID
		public RuleCall getUsuarioIDTerminalRuleCall_1_0() { return cUsuarioIDTerminalRuleCall_1_0; }
		
		//'Contraseña:'
		public Keyword getContraseAKeyword_2() { return cContraseAKeyword_2; }
		
		//contrasena=STRING
		public Assignment getContrasenaAssignment_3() { return cContrasenaAssignment_3; }
		
		//STRING
		public RuleCall getContrasenaSTRINGTerminalRuleCall_3_0() { return cContrasenaSTRINGTerminalRuleCall_3_0; }
	}
	public class DispositivosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.Dispositivos");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCodigoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCodigoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCodigoIDTerminalRuleCall_1_0 = (RuleCall)cCodigoAssignment_1.eContents().get(0);
		private final Keyword cSensorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNombreAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNombreTiposDispositivoEnumRuleCall_3_0 = (RuleCall)cNombreAssignment_3.eContents().get(0);
		private final Assignment cTemperaturaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTemperaturaSTRINGTerminalRuleCall_4_0 = (RuleCall)cTemperaturaAssignment_4.eContents().get(0);
		private final Assignment cAccionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAccionAccionParserRuleCall_5_0 = (RuleCall)cAccionAssignment_5.eContents().get(0);
		
		//Dispositivos:
		//	'Codigo:' codigo=ID 'Sensor' nombre=TiposDispositivo temperatura=STRING? accion=accion;
		@Override public ParserRule getRule() { return rule; }
		
		//'Codigo:' codigo=ID 'Sensor' nombre=TiposDispositivo temperatura=STRING? accion=accion
		public Group getGroup() { return cGroup; }
		
		//'Codigo:'
		public Keyword getCodigoKeyword_0() { return cCodigoKeyword_0; }
		
		//codigo=ID
		public Assignment getCodigoAssignment_1() { return cCodigoAssignment_1; }
		
		//ID
		public RuleCall getCodigoIDTerminalRuleCall_1_0() { return cCodigoIDTerminalRuleCall_1_0; }
		
		//'Sensor'
		public Keyword getSensorKeyword_2() { return cSensorKeyword_2; }
		
		//nombre=TiposDispositivo
		public Assignment getNombreAssignment_3() { return cNombreAssignment_3; }
		
		//TiposDispositivo
		public RuleCall getNombreTiposDispositivoEnumRuleCall_3_0() { return cNombreTiposDispositivoEnumRuleCall_3_0; }
		
		//temperatura=STRING?
		public Assignment getTemperaturaAssignment_4() { return cTemperaturaAssignment_4; }
		
		//STRING
		public RuleCall getTemperaturaSTRINGTerminalRuleCall_4_0() { return cTemperaturaSTRINGTerminalRuleCall_4_0; }
		
		//accion=accion
		public Assignment getAccionAssignment_5() { return cAccionAssignment_5; }
		
		//accion
		public RuleCall getAccionAccionParserRuleCall_5_0() { return cAccionAccionParserRuleCall_5_0; }
	}
	public class AccionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.accion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuieroKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAccionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreAccionNombreAccionEnumRuleCall_1_0 = (RuleCall)cNombreAccionAssignment_1.eContents().get(0);
		private final Assignment cNumeroAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumeroNumeroParserRuleCall_2_0 = (RuleCall)cNumeroAssignment_2.eContents().get(0);
		private final Assignment cDescripcionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_3_0 = (RuleCall)cDescripcionAssignment_3.eContents().get(0);
		
		//accion:
		//	'quiero' nombreAccion=NombreAccion numero=numero? descripcion=STRING?;
		@Override public ParserRule getRule() { return rule; }
		
		//'quiero' nombreAccion=NombreAccion numero=numero? descripcion=STRING?
		public Group getGroup() { return cGroup; }
		
		//'quiero'
		public Keyword getQuieroKeyword_0() { return cQuieroKeyword_0; }
		
		//nombreAccion=NombreAccion
		public Assignment getNombreAccionAssignment_1() { return cNombreAccionAssignment_1; }
		
		//NombreAccion
		public RuleCall getNombreAccionNombreAccionEnumRuleCall_1_0() { return cNombreAccionNombreAccionEnumRuleCall_1_0; }
		
		//numero=numero?
		public Assignment getNumeroAssignment_2() { return cNumeroAssignment_2; }
		
		//numero
		public RuleCall getNumeroNumeroParserRuleCall_2_0() { return cNumeroNumeroParserRuleCall_2_0; }
		
		//descripcion=STRING?
		public Assignment getDescripcionAssignment_3() { return cDescripcionAssignment_3; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_3_0() { return cDescripcionSTRINGTerminalRuleCall_3_0; }
	}
	public class NumeroElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.numero");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//numero:
		//	INT+ '.'? INT*;
		@Override public ParserRule getRule() { return rule; }
		
		//INT+ '.'? INT*
		public Group getGroup() { return cGroup; }
		
		//INT+
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'?
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT*
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	
	public class TipoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.Tipo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDELAVALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDELAVALDELAVALKeyword_0_0 = (Keyword)cDELAVALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSIEMENSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSIEMENSSIEMENSKeyword_1_0 = (Keyword)cSIEMENSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTABLETEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTABLETTABLETKeyword_2_0 = (Keyword)cTABLETEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMOVILEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMOVILMOVILKeyword_3_0 = (Keyword)cMOVILEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cORDENADOREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cORDENADORORDENADORKeyword_4_0 = (Keyword)cORDENADOREnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Tipo:
		//	DELAVAL | SIEMENS | TABLET | MOVIL | ORDENADOR;
		public EnumRule getRule() { return rule; }
		
		//DELAVAL | SIEMENS | TABLET | MOVIL | ORDENADOR
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DELAVAL
		public EnumLiteralDeclaration getDELAVALEnumLiteralDeclaration_0() { return cDELAVALEnumLiteralDeclaration_0; }
		
		//"DELAVAL"
		public Keyword getDELAVALDELAVALKeyword_0_0() { return cDELAVALDELAVALKeyword_0_0; }
		
		//SIEMENS
		public EnumLiteralDeclaration getSIEMENSEnumLiteralDeclaration_1() { return cSIEMENSEnumLiteralDeclaration_1; }
		
		//"SIEMENS"
		public Keyword getSIEMENSSIEMENSKeyword_1_0() { return cSIEMENSSIEMENSKeyword_1_0; }
		
		//TABLET
		public EnumLiteralDeclaration getTABLETEnumLiteralDeclaration_2() { return cTABLETEnumLiteralDeclaration_2; }
		
		//"TABLET"
		public Keyword getTABLETTABLETKeyword_2_0() { return cTABLETTABLETKeyword_2_0; }
		
		//MOVIL
		public EnumLiteralDeclaration getMOVILEnumLiteralDeclaration_3() { return cMOVILEnumLiteralDeclaration_3; }
		
		//"MOVIL"
		public Keyword getMOVILMOVILKeyword_3_0() { return cMOVILMOVILKeyword_3_0; }
		
		//ORDENADOR
		public EnumLiteralDeclaration getORDENADOREnumLiteralDeclaration_4() { return cORDENADOREnumLiteralDeclaration_4; }
		
		//"ORDENADOR"
		public Keyword getORDENADORORDENADORKeyword_4_0() { return cORDENADORORDENADORKeyword_4_0; }
	}
	public class TiposDispositivoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.TiposDispositivo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCAMARAEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCAMARACAMARAKeyword_0_0 = (Keyword)cCAMARAEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTEMPERATURAEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTEMPERATURATEMPERATURAKeyword_1_0 = (Keyword)cTEMPERATURAEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFUEGO_HUMOEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFUEGO_HUMOFUEGO_HUMOKeyword_2_0 = (Keyword)cFUEGO_HUMOEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCO2EnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCO2CO2Keyword_3_0 = (Keyword)cCO2EnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGASEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGASGASKeyword_4_0 = (Keyword)cGASEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPRESENCIAEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPRESENCIAPRESENCIAKeyword_5_0 = (Keyword)cPRESENCIAEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMAGNETICOEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMAGNETICOMAGNETICOKeyword_6_0 = (Keyword)cMAGNETICOEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cROTURA_CRISTALEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cROTURA_CRISTALROTURA_CRISTALKeyword_7_0 = (Keyword)cROTURA_CRISTALEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cBARRERA_SEGURIDADEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cBARRERA_SEGURIDADBARRERA_SEGURIDADKeyword_8_0 = (Keyword)cBARRERA_SEGURIDADEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cLUMINOSIDADEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cLUMINOSIDADLUMINOSIDADKeyword_9_0 = (Keyword)cLUMINOSIDADEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cEMERGENCIAEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cEMERGENCIAEMERGENCIAKeyword_10_0 = (Keyword)cEMERGENCIAEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cINUNDACIONEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cINUNDACIONINUNDACIONKeyword_11_0 = (Keyword)cINUNDACIONEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cVIENTOEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cVIENTOVIENTOKeyword_12_0 = (Keyword)cVIENTOEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cLLUVIAEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cLLUVIALLUVIAKeyword_13_0 = (Keyword)cLLUVIAEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cESTACION_METEOROLOGICAEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cESTACION_METEOROLOGICAESTACION_METEOROLOGICAKeyword_14_0 = (Keyword)cESTACION_METEOROLOGICAEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cSISTEMA_IDENTIFICACIONEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cSISTEMA_IDENTIFICACIONSISTEMA_IDENTIFICACIONKeyword_15_0 = (Keyword)cSISTEMA_IDENTIFICACIONEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cINFRARROJOSEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cINFRARROJOSINFRARROJOSKeyword_16_0 = (Keyword)cINFRARROJOSEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cRADIOFRECUENCIAEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cRADIOFRECUENCIARADIOFRECUENCIAKeyword_17_0 = (Keyword)cRADIOFRECUENCIAEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cMECEDORAEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cMECEDORAMECEDORAKeyword_18_0 = (Keyword)cMECEDORAEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cPULSOMETRO_GANADOEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cPULSOMETRO_GANADOPULSOMETRO_GANADOKeyword_19_0 = (Keyword)cPULSOMETRO_GANADOEnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cDEPOSITO_LECHEEnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cDEPOSITO_LECHEDEPOSITO_LECHEKeyword_20_0 = (Keyword)cDEPOSITO_LECHEEnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cROBOT_LIMPIADOREnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cROBOT_LIMPIADORROBOT_LIMPIADORKeyword_21_0 = (Keyword)cROBOT_LIMPIADOREnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cNEVERASEnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cNEVERASNEVERASKeyword_22_0 = (Keyword)cNEVERASEnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cLUZEnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cLUZLUZKeyword_23_0 = (Keyword)cLUZEnumLiteralDeclaration_23.eContents().get(0);
		
		//enum TiposDispositivo:
		//	CAMARA | TEMPERATURA | FUEGO_HUMO | CO2 | GAS | PRESENCIA | MAGNETICO | ROTURA_CRISTAL
		//	| BARRERA_SEGURIDAD | LUMINOSIDAD | EMERGENCIA | INUNDACION | VIENTO | LLUVIA | ESTACION_METEOROLOGICA |
		//	SISTEMA_IDENTIFICACION | INFRARROJOS | RADIOFRECUENCIA | MECEDORA | PULSOMETRO_GANADO | DEPOSITO_LECHE |
		//	ROBOT_LIMPIADOR | NEVERAS | LUZ;
		public EnumRule getRule() { return rule; }
		
		//CAMARA | TEMPERATURA | FUEGO_HUMO | CO2 | GAS | PRESENCIA | MAGNETICO | ROTURA_CRISTAL | BARRERA_SEGURIDAD | LUMINOSIDAD
		//| EMERGENCIA | INUNDACION | VIENTO | LLUVIA | ESTACION_METEOROLOGICA | SISTEMA_IDENTIFICACION | INFRARROJOS |
		//RADIOFRECUENCIA | MECEDORA | PULSOMETRO_GANADO | DEPOSITO_LECHE | ROBOT_LIMPIADOR | NEVERAS | LUZ
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CAMARA
		public EnumLiteralDeclaration getCAMARAEnumLiteralDeclaration_0() { return cCAMARAEnumLiteralDeclaration_0; }
		
		//"CAMARA"
		public Keyword getCAMARACAMARAKeyword_0_0() { return cCAMARACAMARAKeyword_0_0; }
		
		//TEMPERATURA
		public EnumLiteralDeclaration getTEMPERATURAEnumLiteralDeclaration_1() { return cTEMPERATURAEnumLiteralDeclaration_1; }
		
		//"TEMPERATURA"
		public Keyword getTEMPERATURATEMPERATURAKeyword_1_0() { return cTEMPERATURATEMPERATURAKeyword_1_0; }
		
		//FUEGO_HUMO
		public EnumLiteralDeclaration getFUEGO_HUMOEnumLiteralDeclaration_2() { return cFUEGO_HUMOEnumLiteralDeclaration_2; }
		
		//"FUEGO_HUMO"
		public Keyword getFUEGO_HUMOFUEGO_HUMOKeyword_2_0() { return cFUEGO_HUMOFUEGO_HUMOKeyword_2_0; }
		
		//CO2
		public EnumLiteralDeclaration getCO2EnumLiteralDeclaration_3() { return cCO2EnumLiteralDeclaration_3; }
		
		//"CO2"
		public Keyword getCO2CO2Keyword_3_0() { return cCO2CO2Keyword_3_0; }
		
		//GAS
		public EnumLiteralDeclaration getGASEnumLiteralDeclaration_4() { return cGASEnumLiteralDeclaration_4; }
		
		//"GAS"
		public Keyword getGASGASKeyword_4_0() { return cGASGASKeyword_4_0; }
		
		//PRESENCIA
		public EnumLiteralDeclaration getPRESENCIAEnumLiteralDeclaration_5() { return cPRESENCIAEnumLiteralDeclaration_5; }
		
		//"PRESENCIA"
		public Keyword getPRESENCIAPRESENCIAKeyword_5_0() { return cPRESENCIAPRESENCIAKeyword_5_0; }
		
		//MAGNETICO
		public EnumLiteralDeclaration getMAGNETICOEnumLiteralDeclaration_6() { return cMAGNETICOEnumLiteralDeclaration_6; }
		
		//"MAGNETICO"
		public Keyword getMAGNETICOMAGNETICOKeyword_6_0() { return cMAGNETICOMAGNETICOKeyword_6_0; }
		
		//ROTURA_CRISTAL
		public EnumLiteralDeclaration getROTURA_CRISTALEnumLiteralDeclaration_7() { return cROTURA_CRISTALEnumLiteralDeclaration_7; }
		
		//"ROTURA_CRISTAL"
		public Keyword getROTURA_CRISTALROTURA_CRISTALKeyword_7_0() { return cROTURA_CRISTALROTURA_CRISTALKeyword_7_0; }
		
		//BARRERA_SEGURIDAD
		public EnumLiteralDeclaration getBARRERA_SEGURIDADEnumLiteralDeclaration_8() { return cBARRERA_SEGURIDADEnumLiteralDeclaration_8; }
		
		//"BARRERA_SEGURIDAD"
		public Keyword getBARRERA_SEGURIDADBARRERA_SEGURIDADKeyword_8_0() { return cBARRERA_SEGURIDADBARRERA_SEGURIDADKeyword_8_0; }
		
		//LUMINOSIDAD
		public EnumLiteralDeclaration getLUMINOSIDADEnumLiteralDeclaration_9() { return cLUMINOSIDADEnumLiteralDeclaration_9; }
		
		//"LUMINOSIDAD"
		public Keyword getLUMINOSIDADLUMINOSIDADKeyword_9_0() { return cLUMINOSIDADLUMINOSIDADKeyword_9_0; }
		
		//EMERGENCIA
		public EnumLiteralDeclaration getEMERGENCIAEnumLiteralDeclaration_10() { return cEMERGENCIAEnumLiteralDeclaration_10; }
		
		//"EMERGENCIA"
		public Keyword getEMERGENCIAEMERGENCIAKeyword_10_0() { return cEMERGENCIAEMERGENCIAKeyword_10_0; }
		
		//INUNDACION
		public EnumLiteralDeclaration getINUNDACIONEnumLiteralDeclaration_11() { return cINUNDACIONEnumLiteralDeclaration_11; }
		
		//"INUNDACION"
		public Keyword getINUNDACIONINUNDACIONKeyword_11_0() { return cINUNDACIONINUNDACIONKeyword_11_0; }
		
		//VIENTO
		public EnumLiteralDeclaration getVIENTOEnumLiteralDeclaration_12() { return cVIENTOEnumLiteralDeclaration_12; }
		
		//"VIENTO"
		public Keyword getVIENTOVIENTOKeyword_12_0() { return cVIENTOVIENTOKeyword_12_0; }
		
		//LLUVIA
		public EnumLiteralDeclaration getLLUVIAEnumLiteralDeclaration_13() { return cLLUVIAEnumLiteralDeclaration_13; }
		
		//"LLUVIA"
		public Keyword getLLUVIALLUVIAKeyword_13_0() { return cLLUVIALLUVIAKeyword_13_0; }
		
		//ESTACION_METEOROLOGICA
		public EnumLiteralDeclaration getESTACION_METEOROLOGICAEnumLiteralDeclaration_14() { return cESTACION_METEOROLOGICAEnumLiteralDeclaration_14; }
		
		//"ESTACION_METEOROLOGICA"
		public Keyword getESTACION_METEOROLOGICAESTACION_METEOROLOGICAKeyword_14_0() { return cESTACION_METEOROLOGICAESTACION_METEOROLOGICAKeyword_14_0; }
		
		//SISTEMA_IDENTIFICACION
		public EnumLiteralDeclaration getSISTEMA_IDENTIFICACIONEnumLiteralDeclaration_15() { return cSISTEMA_IDENTIFICACIONEnumLiteralDeclaration_15; }
		
		//"SISTEMA_IDENTIFICACION"
		public Keyword getSISTEMA_IDENTIFICACIONSISTEMA_IDENTIFICACIONKeyword_15_0() { return cSISTEMA_IDENTIFICACIONSISTEMA_IDENTIFICACIONKeyword_15_0; }
		
		//INFRARROJOS
		public EnumLiteralDeclaration getINFRARROJOSEnumLiteralDeclaration_16() { return cINFRARROJOSEnumLiteralDeclaration_16; }
		
		//"INFRARROJOS"
		public Keyword getINFRARROJOSINFRARROJOSKeyword_16_0() { return cINFRARROJOSINFRARROJOSKeyword_16_0; }
		
		//RADIOFRECUENCIA
		public EnumLiteralDeclaration getRADIOFRECUENCIAEnumLiteralDeclaration_17() { return cRADIOFRECUENCIAEnumLiteralDeclaration_17; }
		
		//"RADIOFRECUENCIA"
		public Keyword getRADIOFRECUENCIARADIOFRECUENCIAKeyword_17_0() { return cRADIOFRECUENCIARADIOFRECUENCIAKeyword_17_0; }
		
		//MECEDORA
		public EnumLiteralDeclaration getMECEDORAEnumLiteralDeclaration_18() { return cMECEDORAEnumLiteralDeclaration_18; }
		
		//"MECEDORA"
		public Keyword getMECEDORAMECEDORAKeyword_18_0() { return cMECEDORAMECEDORAKeyword_18_0; }
		
		//PULSOMETRO_GANADO
		public EnumLiteralDeclaration getPULSOMETRO_GANADOEnumLiteralDeclaration_19() { return cPULSOMETRO_GANADOEnumLiteralDeclaration_19; }
		
		//"PULSOMETRO_GANADO"
		public Keyword getPULSOMETRO_GANADOPULSOMETRO_GANADOKeyword_19_0() { return cPULSOMETRO_GANADOPULSOMETRO_GANADOKeyword_19_0; }
		
		//DEPOSITO_LECHE
		public EnumLiteralDeclaration getDEPOSITO_LECHEEnumLiteralDeclaration_20() { return cDEPOSITO_LECHEEnumLiteralDeclaration_20; }
		
		//"DEPOSITO_LECHE"
		public Keyword getDEPOSITO_LECHEDEPOSITO_LECHEKeyword_20_0() { return cDEPOSITO_LECHEDEPOSITO_LECHEKeyword_20_0; }
		
		//ROBOT_LIMPIADOR
		public EnumLiteralDeclaration getROBOT_LIMPIADOREnumLiteralDeclaration_21() { return cROBOT_LIMPIADOREnumLiteralDeclaration_21; }
		
		//"ROBOT_LIMPIADOR"
		public Keyword getROBOT_LIMPIADORROBOT_LIMPIADORKeyword_21_0() { return cROBOT_LIMPIADORROBOT_LIMPIADORKeyword_21_0; }
		
		//NEVERAS
		public EnumLiteralDeclaration getNEVERASEnumLiteralDeclaration_22() { return cNEVERASEnumLiteralDeclaration_22; }
		
		//"NEVERAS"
		public Keyword getNEVERASNEVERASKeyword_22_0() { return cNEVERASNEVERASKeyword_22_0; }
		
		//LUZ
		public EnumLiteralDeclaration getLUZEnumLiteralDeclaration_23() { return cLUZEnumLiteralDeclaration_23; }
		
		//"LUZ"
		public Keyword getLUZLUZKeyword_23_0() { return cLUZLUZKeyword_23_0; }
	}
	public class NombreAccionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.gratext.Gratext.NombreAccion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cABRIREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cABRIRABRIRKeyword_0_0 = (Keyword)cABRIREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cENVIAREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cENVIARENVIARKeyword_1_0 = (Keyword)cENVIAREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSACAREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSACARSACARKeyword_2_0 = (Keyword)cSACAREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCERRAREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCERRARCERRARKeyword_3_0 = (Keyword)cCERRAREnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cESTADOEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cESTADOESTADOKeyword_4_0 = (Keyword)cESTADOEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cGRABAREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cGRABARGRABARKeyword_5_0 = (Keyword)cGRABAREnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDETECTAREnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDETECTARDETECTARKeyword_6_0 = (Keyword)cDETECTAREnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cENCENDEREnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cENCENDERENCENDERKeyword_7_0 = (Keyword)cENCENDEREnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cAPAGAREnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cAPAGARAPAGARKeyword_8_0 = (Keyword)cAPAGAREnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cAUMENTAREnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cAUMENTARAUMENTARKeyword_9_0 = (Keyword)cAUMENTAREnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cDISMINUIREnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cDISMINUIRDISMINUIRKeyword_10_0 = (Keyword)cDISMINUIREnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cCOMPROBAREnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cCOMPROBARCOMPROBARKeyword_11_0 = (Keyword)cCOMPROBAREnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cACTIVAREnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cACTIVARACTIVARKeyword_12_0 = (Keyword)cACTIVAREnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cDESACTIVAREnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cDESACTIVARDESACTIVARKeyword_13_0 = (Keyword)cDESACTIVAREnumLiteralDeclaration_13.eContents().get(0);
		
		//enum NombreAccion:
		//	ABRIR | ENVIAR | SACAR | CERRAR | ESTADO | GRABAR | DETECTAR | ENCENDER | APAGAR | AUMENTAR | DISMINUIR
		//	| COMPROBAR | ACTIVAR | DESACTIVAR;
		public EnumRule getRule() { return rule; }
		
		//ABRIR | ENVIAR | SACAR | CERRAR | ESTADO | GRABAR | DETECTAR | ENCENDER | APAGAR | AUMENTAR | DISMINUIR | COMPROBAR |
		//ACTIVAR | DESACTIVAR
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ABRIR
		public EnumLiteralDeclaration getABRIREnumLiteralDeclaration_0() { return cABRIREnumLiteralDeclaration_0; }
		
		//"ABRIR"
		public Keyword getABRIRABRIRKeyword_0_0() { return cABRIRABRIRKeyword_0_0; }
		
		//ENVIAR
		public EnumLiteralDeclaration getENVIAREnumLiteralDeclaration_1() { return cENVIAREnumLiteralDeclaration_1; }
		
		//"ENVIAR"
		public Keyword getENVIARENVIARKeyword_1_0() { return cENVIARENVIARKeyword_1_0; }
		
		//SACAR
		public EnumLiteralDeclaration getSACAREnumLiteralDeclaration_2() { return cSACAREnumLiteralDeclaration_2; }
		
		//"SACAR"
		public Keyword getSACARSACARKeyword_2_0() { return cSACARSACARKeyword_2_0; }
		
		//CERRAR
		public EnumLiteralDeclaration getCERRAREnumLiteralDeclaration_3() { return cCERRAREnumLiteralDeclaration_3; }
		
		//"CERRAR"
		public Keyword getCERRARCERRARKeyword_3_0() { return cCERRARCERRARKeyword_3_0; }
		
		//ESTADO
		public EnumLiteralDeclaration getESTADOEnumLiteralDeclaration_4() { return cESTADOEnumLiteralDeclaration_4; }
		
		//"ESTADO"
		public Keyword getESTADOESTADOKeyword_4_0() { return cESTADOESTADOKeyword_4_0; }
		
		//GRABAR
		public EnumLiteralDeclaration getGRABAREnumLiteralDeclaration_5() { return cGRABAREnumLiteralDeclaration_5; }
		
		//"GRABAR"
		public Keyword getGRABARGRABARKeyword_5_0() { return cGRABARGRABARKeyword_5_0; }
		
		//DETECTAR
		public EnumLiteralDeclaration getDETECTAREnumLiteralDeclaration_6() { return cDETECTAREnumLiteralDeclaration_6; }
		
		//"DETECTAR"
		public Keyword getDETECTARDETECTARKeyword_6_0() { return cDETECTARDETECTARKeyword_6_0; }
		
		//ENCENDER
		public EnumLiteralDeclaration getENCENDEREnumLiteralDeclaration_7() { return cENCENDEREnumLiteralDeclaration_7; }
		
		//"ENCENDER"
		public Keyword getENCENDERENCENDERKeyword_7_0() { return cENCENDERENCENDERKeyword_7_0; }
		
		//APAGAR
		public EnumLiteralDeclaration getAPAGAREnumLiteralDeclaration_8() { return cAPAGAREnumLiteralDeclaration_8; }
		
		//"APAGAR"
		public Keyword getAPAGARAPAGARKeyword_8_0() { return cAPAGARAPAGARKeyword_8_0; }
		
		//AUMENTAR
		public EnumLiteralDeclaration getAUMENTAREnumLiteralDeclaration_9() { return cAUMENTAREnumLiteralDeclaration_9; }
		
		//"AUMENTAR"
		public Keyword getAUMENTARAUMENTARKeyword_9_0() { return cAUMENTARAUMENTARKeyword_9_0; }
		
		//DISMINUIR
		public EnumLiteralDeclaration getDISMINUIREnumLiteralDeclaration_10() { return cDISMINUIREnumLiteralDeclaration_10; }
		
		//"DISMINUIR"
		public Keyword getDISMINUIRDISMINUIRKeyword_10_0() { return cDISMINUIRDISMINUIRKeyword_10_0; }
		
		//COMPROBAR
		public EnumLiteralDeclaration getCOMPROBAREnumLiteralDeclaration_11() { return cCOMPROBAREnumLiteralDeclaration_11; }
		
		//"COMPROBAR"
		public Keyword getCOMPROBARCOMPROBARKeyword_11_0() { return cCOMPROBARCOMPROBARKeyword_11_0; }
		
		//ACTIVAR
		public EnumLiteralDeclaration getACTIVAREnumLiteralDeclaration_12() { return cACTIVAREnumLiteralDeclaration_12; }
		
		//"ACTIVAR"
		public Keyword getACTIVARACTIVARKeyword_12_0() { return cACTIVARACTIVARKeyword_12_0; }
		
		//DESACTIVAR
		public EnumLiteralDeclaration getDESACTIVAREnumLiteralDeclaration_13() { return cDESACTIVAREnumLiteralDeclaration_13; }
		
		//"DESACTIVAR"
		public Keyword getDESACTIVARDESACTIVARKeyword_13_0() { return cDESACTIVARDESACTIVARKeyword_13_0; }
	}
	
	private final GranjaElements pGranja;
	private final LoginElements pLogin;
	private final DispositivosElements pDispositivos;
	private final AccionElements pAccion;
	private final NumeroElements pNumero;
	private final TipoElements eTipo;
	private final TiposDispositivoElements eTiposDispositivo;
	private final NombreAccionElements eNombreAccion;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GratextGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGranja = new GranjaElements();
		this.pLogin = new LoginElements();
		this.pDispositivos = new DispositivosElements();
		this.pAccion = new AccionElements();
		this.pNumero = new NumeroElements();
		this.eTipo = new TipoElements();
		this.eTiposDispositivo = new TiposDispositivoElements();
		this.eNombreAccion = new NombreAccionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.dsl.gratext.Gratext".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Granja:
	//	'Granja:' nombreGranja=ID
	//	'Centralita:' tipo=Tipo
	//	login=login?
	//	'Dispositivos{' dispositivos+=Dispositivos* '}';
	public GranjaElements getGranjaAccess() {
		return pGranja;
	}
	
	public ParserRule getGranjaRule() {
		return getGranjaAccess().getRule();
	}
	
	//login:
	//	'Usuario:' usuario=ID
	//	'Contraseña:' contrasena=STRING;
	public LoginElements getLoginAccess() {
		return pLogin;
	}
	
	public ParserRule getLoginRule() {
		return getLoginAccess().getRule();
	}
	
	//Dispositivos:
	//	'Codigo:' codigo=ID 'Sensor' nombre=TiposDispositivo temperatura=STRING? accion=accion;
	public DispositivosElements getDispositivosAccess() {
		return pDispositivos;
	}
	
	public ParserRule getDispositivosRule() {
		return getDispositivosAccess().getRule();
	}
	
	//accion:
	//	'quiero' nombreAccion=NombreAccion numero=numero? descripcion=STRING?;
	public AccionElements getAccionAccess() {
		return pAccion;
	}
	
	public ParserRule getAccionRule() {
		return getAccionAccess().getRule();
	}
	
	//numero:
	//	INT+ '.'? INT*;
	public NumeroElements getNumeroAccess() {
		return pNumero;
	}
	
	public ParserRule getNumeroRule() {
		return getNumeroAccess().getRule();
	}
	
	//enum Tipo:
	//	DELAVAL | SIEMENS | TABLET | MOVIL | ORDENADOR;
	public TipoElements getTipoAccess() {
		return eTipo;
	}
	
	public EnumRule getTipoRule() {
		return getTipoAccess().getRule();
	}
	
	//enum TiposDispositivo:
	//	CAMARA | TEMPERATURA | FUEGO_HUMO | CO2 | GAS | PRESENCIA | MAGNETICO | ROTURA_CRISTAL
	//	| BARRERA_SEGURIDAD | LUMINOSIDAD | EMERGENCIA | INUNDACION | VIENTO | LLUVIA | ESTACION_METEOROLOGICA |
	//	SISTEMA_IDENTIFICACION | INFRARROJOS | RADIOFRECUENCIA | MECEDORA | PULSOMETRO_GANADO | DEPOSITO_LECHE |
	//	ROBOT_LIMPIADOR | NEVERAS | LUZ;
	public TiposDispositivoElements getTiposDispositivoAccess() {
		return eTiposDispositivo;
	}
	
	public EnumRule getTiposDispositivoRule() {
		return getTiposDispositivoAccess().getRule();
	}
	
	//enum NombreAccion:
	//	ABRIR | ENVIAR | SACAR | CERRAR | ESTADO | GRABAR | DETECTAR | ENCENDER | APAGAR | AUMENTAR | DISMINUIR
	//	| COMPROBAR | ACTIVAR | DESACTIVAR;
	public NombreAccionElements getNombreAccionAccess() {
		return eNombreAccion;
	}
	
	public EnumRule getNombreAccionRule() {
		return getNombreAccionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
