/*
 * generated by Xtext 2.11.0
 */
package org.xtext.dsl.gratext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.dsl.gratext.ide.contentassist.antlr.internal.InternalGratextParser;
import org.xtext.dsl.gratext.services.GratextGrammarAccess;

public class GratextParser extends AbstractContentAssistParser {

	@Inject
	private GratextGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGratextParser createParser() {
		InternalGratextParser result = new InternalGratextParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDatosAccess().getAlternatives(), "rule__Datos__Alternatives");
					put(grammarAccess.getTipoAccess().getAlternatives(), "rule__Tipo__Alternatives");
					put(grammarAccess.getTiposDispositivoAccess().getAlternatives(), "rule__TiposDispositivo__Alternatives");
					put(grammarAccess.getNombreAccionAccess().getAlternatives(), "rule__NombreAccion__Alternatives");
					put(grammarAccess.getGranjaAccess().getGroup(), "rule__Granja__Group__0");
					put(grammarAccess.getLoginAccess().getGroup(), "rule__Login__Group__0");
					put(grammarAccess.getDispositivosAccess().getGroup(), "rule__Dispositivos__Group__0");
					put(grammarAccess.getAccionAccess().getGroup(), "rule__Accion__Group__0");
					put(grammarAccess.getNumeroAccess().getGroup(), "rule__Numero__Group__0");
					put(grammarAccess.getIdNumeroAccess().getGroup(), "rule__IdNumero__Group__0");
					put(grammarAccess.getGranjaAccess().getNombreGranjaAssignment_1(), "rule__Granja__NombreGranjaAssignment_1");
					put(grammarAccess.getGranjaAccess().getTipoAssignment_3(), "rule__Granja__TipoAssignment_3");
					put(grammarAccess.getGranjaAccess().getLoginAssignment_4(), "rule__Granja__LoginAssignment_4");
					put(grammarAccess.getGranjaAccess().getDispositivosAssignment_6(), "rule__Granja__DispositivosAssignment_6");
					put(grammarAccess.getLoginAccess().getUsuarioAssignment_1(), "rule__Login__UsuarioAssignment_1");
					put(grammarAccess.getLoginAccess().getContrasenaAssignment_3(), "rule__Login__ContrasenaAssignment_3");
					put(grammarAccess.getDispositivosAccess().getCodigoAssignment_1(), "rule__Dispositivos__CodigoAssignment_1");
					put(grammarAccess.getDispositivosAccess().getNombreAssignment_3(), "rule__Dispositivos__NombreAssignment_3");
					put(grammarAccess.getDispositivosAccess().getTemperaturaAssignment_4(), "rule__Dispositivos__TemperaturaAssignment_4");
					put(grammarAccess.getDispositivosAccess().getAccionAssignment_5(), "rule__Dispositivos__AccionAssignment_5");
					put(grammarAccess.getAccionAccess().getNombreAccionAssignment_1(), "rule__Accion__NombreAccionAssignment_1");
					put(grammarAccess.getAccionAccess().getNumeroAssignment_2(), "rule__Accion__NumeroAssignment_2");
					put(grammarAccess.getAccionAccess().getDescripcionAssignment_3(), "rule__Accion__DescripcionAssignment_3");
					put(grammarAccess.getNumeroAccess().getIdNumeroAssignment_0(), "rule__Numero__IdNumeroAssignment_0");
					put(grammarAccess.getNumeroAccess().getDatosAssignment_1(), "rule__Numero__DatosAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GratextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GratextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
